# Generated by Django 3.2 on 2022-02-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220202_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='url',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='url',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
