# Generated by Django 3.2 on 2022-02-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220202_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='url',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='url',
        ),
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
