# Generated by Django 3.2 on 2022-02-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220202_1746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
