# Generated by Django 3.2 on 2022-02-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo',
            new_name='title',
        ),
    ]
